let players=[];
const capacity=15;
const teamSize=5;
let rules=[];
let transactions=[];
let diarists=[];
let teams=[[],[],[]], attendanceCount=0, myAttendance={status:'pendente',justificativa:''}, attendanceNames=new Set(), attendanceRecords={};
function stars(n){return '★'.repeat(n)+'<span style="color:#ddd">★</span>'.repeat(5-n)}
function render(){
 const confirmed=attendanceCount, vacancies=Math.max(capacity-confirmed,0), percent=Math.min((confirmed/capacity)*100,100);
 document.querySelector('#confirmedCount').textContent=confirmed;document.querySelector('#capacityCount').textContent=capacity;document.querySelector('#confirmationProgress').style.width=percent+'%';document.querySelector('#availableSpots').textContent=`Clube do Diário · ${vacancies} ${vacancies===1?'vaga':'vagas'}`;document.querySelector('#drawConfirmedCount').textContent=confirmed;document.querySelector('#drawVacancyCount').textContent=`${vacancies} ${vacancies===1?'vaga restante':'vagas restantes'}`;
 const contribution=[...players].sort((a,b)=>(b.g+b.a)-(a.g+a.a));const assists=[...players].sort((a,b)=>b.a-a.a);const scorers=[...players].sort((a,b)=>b.g-a.g);
 document.querySelector('#leaderboard').innerHTML=players.length?contribution.slice(0,4).map((p,i)=>`<div class="rank-row"><b class="rank-num">0${i+1}</b><span class="rank-face" style="background:${p.color}">${p.face}</span><div class="rank-name">${p.name}<small>${p.g} gols · ${p.a} assistências</small></div><div class="rank-score">${p.g+p.a}<small> PART.</small></div></div>`).join(''):'<p class="empty-state">Ainda não há estatísticas de jogadores.</p>';
 document.querySelector('#assistLeaderboard').innerHTML=players.length?assists.slice(0,4).map((p,i)=>`<div class="rank-row"><b class="rank-num">0${i+1}</b><span class="rank-face" style="background:${p.color}">${p.face}</span><div class="rank-name">${p.name}<small>${p.pos} · ${p.g} gols</small></div><div class="rank-score">${p.a}<small> ASSIST.</small></div></div>`).join(''):'<p class="empty-state">Ainda não há assistências registradas.</p>';
 document.querySelector('#goalsLeaderboard').innerHTML=players.length?scorers.slice(0,5).map((p,i)=>`<div class="rank-row"><b class="rank-num">0${i+1}</b><span class="rank-face" style="background:${p.color}">${p.face}</span><div class="rank-name">${p.name}<small>${p.pos} · ${p.j} peladas</small></div><div class="rank-score">${p.g}<small> GOLS</small></div></div>`).join(''):'<p class="empty-state">Ainda não há gols registrados.</p>';
 document.querySelector('#playersList').innerHTML=players.length?players.map(p=>{const record=attendanceRecords[p.name]||{status:'pendente',justificativa:''};const status=record.status;const photo=p.photo_url?`<img class="tiny-face player-photo" src="${p.photo_url}" alt="Foto de ${p.name}">`:`<span class="tiny-face" style="background:${p.color}">${p.face}</span>`;return `<div class="player-row attendance-${status}"><div class="player-info">${photo}<div><b>${p.name}</b><small>Nº ${p.jersey_number||'—'} · ${p.foot} · “${p.phrase}”</small></div></div><b data-label="Camisa">${p.jersey_number||'—'}</b><span data-label="Posição">${p.pos}</span><span class="stars" data-label="Estrelas">${stars(p.stars)}</span><b data-label="Gols">${p.g}</b><b data-label="Assistências">${p.a}</b><b data-label="Jogos">${p.j}</b><div class="player-actions admin-only"><div class="attendance-buttons"><button class="attendance-action confirmed-action ${status==='confirmado'?'is-active':''}" data-player-name="${p.name}" data-attendance-status="confirmado" type="button">✓ Confirmado</button><button class="attendance-action absent-action ${status==='ausente'?'is-active':''}" data-player-name="${p.name}" data-attendance-status="ausente" type="button">× Ausente</button></div><textarea class="attendance-justification admin-justification" data-player-name="${p.name}" ${status==='ausente'?'':'hidden'} maxlength="500" placeholder="Justificativa da ausência (opcional)">${record.justificativa||''}</textarea><div class="admin-row-actions"><button class="row-actions edit-stats" data-id="${p.id}" data-name="${p.name}" data-goals="${p.g}" data-assists="${p.a}" data-games="${p.j}" data-stars="${p.stars}" data-jersey="${p.jersey_number||''}" aria-label="Editar estatísticas e estrelas de ${p.name}">⚽</button><button class="row-actions delete-player" data-id="${p.id}" aria-label="Excluir ${p.name}">×</button></div></div></div>`}).join(''):'<p class="empty-state">Nenhum jogador cadastrado ainda.</p>';

 const confirmedPlayers=[...attendanceNames].map(name=>players.find(player=>player.name===name)||{name,pos:'Diarista',jersey_number:'—',photo_url:''});
 const absentPlayers=Object.values(attendanceRecords).filter(record=>record.status==='ausente').map(record=>players.find(player=>player.name===record.player_name)||{name:record.player_name,pos:'Diarista',jersey_number:'—',photo_url:''});
 const attendanceCard=(player,label,kind)=>`<article class="confirmed-player-card ${kind}">${player.photo_url?`<img class="confirmed-player-photo" src="${player.photo_url}" alt="Foto de ${player.name}">`:`<span class="confirmed-player-photo fallback">⚽</span>`}<div><b>${player.name}</b><small>Nº ${player.jersey_number||'—'} · ${player.pos}</small><span>${label}</span></div></article>`;
 document.querySelector('#confirmedPlayersList').innerHTML=confirmedPlayers.length?confirmedPlayers.map(player=>attendanceCard(player,'✓ Confirmado','confirmed')).join(''):'<p class="empty-state">Ainda não há jogadores confirmados para esta pelada.</p>';
 document.querySelector('#absentPlayersList').innerHTML=absentPlayers.length?absentPlayers.map(player=>attendanceCard(player,'× Ausente','absent')).join(''):'<p class="empty-state">Ainda não há ausências informadas para esta pelada.</p>';
 document.querySelector('#teamsGrid').innerHTML=teams.map((team,i)=>{let power=team.length?(team.reduce((a,p)=>a+p.stars,0)/team.length).toFixed(1):'—';let name=`TIME ${i+1}`;let slots=[...team,...Array(Math.max(teamSize-team.length,0)).fill(null)];return `<article class="team-card"><div class="team-card-header"><div><small>${name}</small><h2>${name}</h2></div><div class="team-power"><b>${power}</b><span>FORÇA MÉDIA</span></div></div><div class="squad">${slots.map(p=>p?`<div class="squad-row"><span class="player-face" style="background:${p.color}">${p.face}</span><div><b>${p.name}</b><small>${p.foot} · ${p.phrase}</small></div><span class="position">${p.pos.toUpperCase()}</span><span class="stars">${stars(p.stars)}</span></div>`:`<div class="squad-row vacancy"><span class="player-face">+</span><div><b>Vaga disponível</b><small>Aguardando confirmação</small></div><span class="position">—</span><span class="stars">—</span></div>`).join('')}</div></article>`}).join('');

 document.querySelector('#diaristsList').innerHTML=diarists.length?diarists.map(d=>{const when=d.data_atualizacao?new Date(d.data_atualizacao.replace(' ','T')+'Z').toLocaleString('pt-BR'):'Ainda não confirmou';const approved=d.status==='confirmado'&&Number(d.admin_confirmed)===1;const awaiting=d.status==='confirmado'&&!approved;const canApprove=currentUser?.role==='admin';return `<article class="diarist-row"><div class="diarist-icon">⚽</div><div><b>${d.name}</b><small>${d.status==='confirmado'?'Confirmou em '+when:d.status==='ausente'?'Informou ausência':'Ainda não confirmou'}</small>${d.justificativa?`<small class="diarist-reason">Justificativa: ${d.justificativa}</small>`:''}</div><span class="diarist-status ${approved?'approved':awaiting?'awaiting':'pending'}">${approved?'✓ Aprovado':awaiting?'⏳ Aguardando supervisão':d.status==='ausente'?'× Ausente':'• Pendente'}</span>${awaiting&&canApprove?`<button class="primary-btn approve-diarist" data-player-name="${d.name}" type="button">Aprovar</button>`:''}</article>`}).join(''):'<p class="empty-state">Nenhum diarista cadastrado ainda.</p>';
 document.querySelector('#transactions').innerHTML=transactions.length?transactions.map(t=>`<div class="transaction ${t[3]?'out':''}"><div class="transaction-icon">${t[3]?'↗':'↙'}</div><div><b>${t[0]}</b><small>${t[1]}</small></div><strong>${t[2]}</strong><button class="row-actions admin-only delete-finance" data-id="${t[4]}">×</button></div>`).join(''):'<p class="empty-state">Nenhuma movimentação financeira registrada.</p>';
 document.querySelector('#rulesList').innerHTML=rules.map((r,i)=>`<article class="rule"><b class="rule-num">${String(i+1).padStart(2,'0')}</b><div><h3>${r.title}</h3><p>${r.content}</p></div><button class="row-actions admin-only delete-rule" data-id="${r.id}">×</button></article>`).join('');
}
function openModal(title,body){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalBody').innerHTML=body;document.querySelector('#modal').classList.add('open')}
document.querySelectorAll('[data-page],[data-go]').forEach(b=>b.addEventListener('click',()=>{const page=b.dataset.page||b.dataset.go;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.querySelector('#'+page).classList.add('active-page');document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelector('#breadcrumb').textContent=b.textContent.trim().toUpperCase();document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}));
document.querySelector('#adminToggle').addEventListener('click',()=>{if(currentUser?.role==='admin'){document.body.classList.toggle('admin-mode');const yes=document.body.classList.contains('admin-mode');document.querySelector('#adminToggle').innerHTML=yes?'✓ Modo administrador ativo':'<span>⚙</span> Área do administrador';}else openAuth(true)});
document.querySelector('#menuButton').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
document.querySelector('#closeModal').addEventListener('click',()=>document.querySelector('#modal').classList.remove('open'));
document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')});
document.querySelector('#addPlayer').addEventListener('click',()=>openModal('Cadastrar jogador',`<form class="form-grid" id="playerForm"><input id="playerName" placeholder="Nome do mensalista" required><input id="playerPassword" type="password" placeholder="Senha inicial da conta (mín. 6)" required><input id="playerPhoto" type="file" accept="image/*"><input id="playerJersey" type="number" min="1" max="99" placeholder="Número da camisa" required><select id="playerPosition" required><option value="">Posição</option><option>Atacante</option><option>Meia</option><option>Zagueiro</option><option>Goleiro</option></select><select id="playerFoot" required><option value="">Perna boa</option><option>Destro</option><option>Canhoto</option><option>Ambidestro</option></select><select id="playerStars" required><option value="">Estrelas</option><option value="1">⭐</option><option value="2">⭐⭐</option><option value="3">⭐⭐⭐</option><option value="4">⭐⭐⭐⭐</option><option value="5">⭐⭐⭐⭐⭐</option></select><textarea id="playerPhrase" placeholder="Uma frase do jogador..."></textarea><p class="form-error" id="playerError"></p><button class="primary-btn">Salvar jogador</button></form>`));
document.querySelector('#newTransaction').addEventListener('click',()=>openModal('Lançar movimentação',`<form class="form-grid" id="financeForm"><input id="financeDescription" placeholder="Descrição" required><input id="financeAmount" type="number" min="0.01" step="0.01" placeholder="Valor (R$)" required><select id="financeKind"><option value="income">Entrada</option><option value="expense">Saída</option></select><p class="form-error" id="financeError"></p><button class="primary-btn">Salvar lançamento</button></form>`));
document.querySelector('#addRule').addEventListener('click',()=>openModal('Criar regra',`<form class="form-grid" id="ruleForm"><input id="ruleTitle" placeholder="Título da regra" required><textarea id="ruleContent" placeholder="Descreva a regra..." required></textarea><p class="form-error" id="ruleError"></p><button class="primary-btn">Salvar regra</button></form>`));
document.addEventListener('click',e=>{const button=e.target.closest('.edit-stats');if(!button)return;openModal(`Editar ${button.dataset.name}`,`<form class="form-grid" id="statsForm" data-player-id="${button.dataset.id}"><label class="field-label" for="playerJersey">Número da camisa</label><input id="playerJersey" type="number" min="1" max="99" value="${button.dataset.jersey}" required><label class="field-label" for="playerStars">Nível do jogador</label><select id="playerStars" required><option value="1" ${button.dataset.stars==='1'?'selected':''}>⭐ — 1 estrela</option><option value="2" ${button.dataset.stars==='2'?'selected':''}>⭐⭐ — 2 estrelas</option><option value="3" ${button.dataset.stars==='3'?'selected':''}>⭐⭐⭐ — 3 estrelas</option><option value="4" ${button.dataset.stars==='4'?'selected':''}>⭐⭐⭐⭐ — 4 estrelas</option><option value="5" ${button.dataset.stars==='5'?'selected':''}>⭐⭐⭐⭐⭐ — 5 estrelas</option></select><label class="field-label" for="playerGoals">Quantidade de gols</label><input id="playerGoals" type="number" min="0" step="1" inputmode="numeric" value="${button.dataset.goals}" required><label class="field-label" for="playerAssists">Quantidade de assistências</label><input id="playerAssists" type="number" min="0" step="1" inputmode="numeric" value="${button.dataset.assists}" required><label class="field-label" for="playerGames">Peladas jogadas</label><input id="playerGames" type="number" min="0" step="1" inputmode="numeric" value="${button.dataset.games}" required><p class="form-error" id="statsError"></p><button class="primary-btn">Salvar alterações</button></form>`)});
function sortearTimes(){
 const confirmados=[...attendanceNames].map(nome=>players.find(player=>player.name===nome)||{name:nome,pos:'Diarista',foot:'—',phrase:'Jogador diarista',stars:3,face:'⚽',color:'#dce5c3'});
 if(!confirmados.length){showSuccess('Ainda não há confirmados','Confirme jogadores na lista antes de realizar o sorteio.');return}
 const embaralhados=confirmados.sort(()=>Math.random()-.5).sort((a,b)=>Number(b.stars)-Number(a.stars));
 teams=[[],[],[]];
 embaralhados.forEach(jogador=>{
   const vagas=teams.filter(time=>time.length<teamSize);
   const menorForca=Math.min(...vagas.map(time=>time.reduce((total,item)=>total+Number(item.stars||3),0)));
   const candidatos=vagas.filter(time=>time.reduce((total,item)=>total+Number(item.stars||3),0)===menorForca);
   candidatos[Math.floor(Math.random()*candidatos.length)].push(jogador);
 });
 render();
 showSuccess('Times sorteados',`${confirmados.length} jogador${confirmados.length===1?'':'es'} distribuído${confirmados.length===1?'':'s'} entre os Times 1, 2 e 3.`);
}
document.querySelector('#reroll').addEventListener('click',sortearTimes);
let currentUser=null, authMode='login', requestingAdmin=false;
const successModal=document.querySelector('#successModal');
function showSuccess(title,message){document.querySelector('#successTitle').textContent=title;document.querySelector('#successMessage').textContent=message;successModal.classList.add('open')}
document.querySelector('#successClose').addEventListener('click',()=>successModal.classList.remove('open'));
successModal.addEventListener('click',event=>{if(event.target===successModal)successModal.classList.remove('open')});

const authModal=document.querySelector('#authModal'), authName=document.querySelector('#authName'), authPosition=document.querySelector('#authPosition'), authFoot=document.querySelector('#authFoot'), authPhrase=document.querySelector('#authPhrase'), authStars=document.querySelector('#authStars'), authAccountType=document.querySelector('#authAccountType'), authPassword=document.querySelector('#authPassword'), authError=document.querySelector('#authError');
function syncAccountFields(){const showProfile=authMode==='signup'&&authAccountType.value==='user';[authPosition,authFoot,authPhrase,authStars].forEach(field=>{field.hidden=!showProfile;field.style.display=showProfile?'':'none'});authPosition.required=showProfile;authFoot.required=showProfile;authPhrase.required=showProfile;authStars.required=showProfile}
function openAuth(admin=false){requestingAdmin=admin;authMode='login';authModal.classList.add('open');authModal.querySelector('.modal').classList.toggle('auth-admin',admin);document.querySelector('#authEyebrow').textContent=admin?'ÁREA RESTRITA':'BEM-VINDO À RESENHA';document.querySelector('#authTitle').textContent=admin?'Entrar como administrador':'Entrar';document.querySelector('#authCopy').textContent=admin?'Informe a senha de administrador para liberar o painel.':'Escolha se você é mensal ou diarista e entre com sua conta.';authName.hidden=admin;authName.required=!admin;authAccountType.hidden=admin;authPosition.hidden=true;authFoot.hidden=true;authPhrase.hidden=true;document.querySelector('#authSubmit').textContent='Entrar';authError.textContent='';authPassword.value='';}
function closeAuth(){authModal.classList.remove('open')}
function updateUser(user){currentUser=user;document.body.classList.toggle('diarist-mode',user?.role==='diarist');document.body.classList.toggle('player-mode',user?.role==='user');document.querySelector('#loginButton').textContent=user?'Olá, '+user.name.split(' ')[0]:'Entrar';document.querySelector('#userAvatar').textContent=user?user.name.slice(0,2).toUpperCase():'?';document.querySelector('#heroGreeting').textContent=user?.name||'Visitante';}
document.querySelector('#loginButton').addEventListener('click',()=>currentUser?fetch('/api/logout',{method:'POST'}).then(()=>{document.body.classList.remove('admin-mode');updateUser(null);loadAttendance()}):openAuth());
document.querySelector('[data-page="profile"]').addEventListener('click',()=>{if(currentUser?.role==='user')loadProfile()});
document.querySelector('#closeAuthModal').addEventListener('click',closeAuth);
authModal.addEventListener('click',e=>{if(e.target===authModal)closeAuth()});
document.querySelectorAll('.auth-tab').forEach(button=>button.addEventListener('click',()=>{requestingAdmin=false;authMode=button.dataset.auth;document.querySelectorAll('.auth-tab').forEach(x=>x.classList.toggle('active',x===button));const creating=authMode==='signup';if(creating){authAccountType.value='diarist';authAccountType.hidden=true}else authAccountType.hidden=false;document.querySelector('#authTitle').textContent=creating?'Cadastro de diarista':'Entrar';document.querySelector('#authCopy').textContent=creating?'Cadastre-se como diarista para entrar na lista de espera. Contas mensais são criadas pela administração.':'Informe se você é mensal ou diarista antes de entrar.';document.querySelector('#authSubmit').textContent=creating?'Criar conta de diarista':'Entrar';authError.textContent='';syncAccountFields()}));
authAccountType.addEventListener('change',syncAccountFields);authAccountType.addEventListener('input',syncAccountFields);
document.addEventListener('click',event=>{const link=event.target.closest('[data-page],[data-go]');if(!link||currentUser?.role!=='diarist')return;const target=link.dataset.page||link.dataset.go;if(['home','players','confirmed','diarists'].includes(target))return;event.preventDefault();document.querySelectorAll('.page').forEach(page=>page.classList.remove('active-page'));document.querySelector('#home').classList.add('active-page');document.querySelectorAll('.nav-link').forEach(item=>item.classList.toggle('active',item.dataset.page==='home'));document.querySelector('#breadcrumb').textContent='VISÃO GERAL';window.scrollTo(0,0)});
document.querySelector('#authForm').addEventListener('submit',async e=>{e.preventDefault();authError.textContent='';const isDiarist=authAccountType.value==='diarist';const payload=requestingAdmin?{admin:true,password:authPassword.value}:authMode==='signup'?(isDiarist?{name:authName.value,password:authPassword.value,account_type:'diarist'}:{name:authName.value,password:authPassword.value,position:authPosition.value,foot:authFoot.value,phrase:authPhrase.value,stars:authStars.value,account_type:'user'}):{name:authName.value,password:authPassword.value,account_type:authAccountType.value};const endpoint=authMode==='signup'&&!requestingAdmin?'/api/signup':'/api/login';const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok){authError.textContent=data.error||'Não foi possível concluir a ação.';return}if(endpoint==='/api/signup'){const typeLabel=isDiarist?'Conta de diarista criada':'Conta mensal criada';closeAuth();showSuccess(typeLabel,'Seu cadastro foi concluído com sucesso. Entre agora para acessar a pelada.');loadPlayers();return}updateUser(data.user);loadAttendance();closeAuth();if(data.user.role==='admin'){document.body.classList.add('admin-mode');document.querySelector('#adminToggle').innerHTML='✓ Modo administrador ativo';loadDiarists()}});
fetch('/api/session').then(r=>r.json()).then(data=>{if(data.user){updateUser(data.user);if(data.user.role==='admin'){document.body.classList.add('admin-mode');document.querySelector('#adminToggle').innerHTML='✓ Modo administrador ativo';loadDiarists()}}loadAttendance()}).catch(()=>{});
async function loadFinance(){try{const response=await fetch('/api/finance');const data=await response.json();transactions=data.transactions.map(t=>[t.description,'Lançamento registrado',`${t.kind==='income'?'+':'−'} R$ ${Number(t.amount).toFixed(2).replace('.',',')}`,t.kind==='expense',t.id]);document.querySelector('#balanceValue').textContent=`R$ ${data.balance.toFixed(2).replace('.',',')}`;document.querySelector('#incomeValue').textContent=`R$ ${data.income.toFixed(2).replace('.',',')}`;document.querySelector('#expenseValue').textContent=`R$ ${data.expense.toFixed(2).replace('.',',')}`;document.querySelector('#homeBalance').textContent=`R$ ${data.balance.toFixed(2).replace('.',',')}`;render()}catch(e){}}
async function loadPlayers(){try{const data=await (await fetch('/api/players')).json();players=data.players.map(p=>({...p,pos:p.position,g:p.goals,a:p.assists,j:p.games,face:'⚽',color:'#dce5c3'}));render()}catch(e){}}
async function loadRules(){try{const data=await (await fetch('/api/rules')).json();rules=data.rules;render()}catch(e){}}
async function loadDiarists(){try{const response=await fetch('/api/diarists');if(!response.ok)return;const data=await response.json();diarists=data.diarists||[];render()}catch(e){}}
async function loadAttendance(){try{const data=await (await fetch('/api/attendance')).json();attendanceCount=data.confirmed;myAttendance=data.my_attendance||data.mine||{status:'pendente',justificativa:''};attendanceNames=new Set(data.confirmed_names||[]);attendanceRecords=Object.fromEntries((data.records||[]).map(record=>[record.player_name,record]));const confirmButton=document.querySelector('#presenceButton'),absentButton=document.querySelector('#absenceButton'),message=document.querySelector('#presenceMessage'),justification=document.querySelector('#absenceJustification');const logged=!!currentUser&&['user','diarist'].includes(currentUser.role);confirmButton.classList.toggle('is-active',myAttendance.status==='confirmado');absentButton.classList.toggle('is-active',myAttendance.status==='ausente');justification.hidden=myAttendance.status!=='ausente';justification.value=myAttendance.justificativa||'';if(!logged){message.textContent='Entre na sua conta para confirmar ou informar ausência.'}else if(myAttendance.status==='confirmado'){message.textContent='Sua presença está confirmada para a próxima pelada.'}else if(myAttendance.status==='ausente'){message.textContent='Sua ausência foi informada. Você pode incluir uma justificativa abaixo.'}else{message.textContent='Selecione Confirmado ou Ausente para a próxima pelada.'}render()}catch(e){}}
async function updateMyAttendance(status,justificativa=''){if(!currentUser||!['user','diarist'].includes(currentUser.role)){openAuth();return}const response=await fetch('/api/attendance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,justificativa})});const data=await response.json();if(!response.ok){showSuccess('Não foi possível atualizar',data.error||'Tente novamente.');return}await loadAttendance();showSuccess(status==='confirmado'?'Presença confirmada':'Ausência informada',status==='confirmado'?'Sua vaga está confirmada para a próxima pelada.':'Você pode reverter a ausência até 2 horas antes da pelada.');}
document.querySelector('#absenceButton').addEventListener('click',()=>updateMyAttendance('ausente',document.querySelector('#absenceJustification').value));
document.querySelector('#presenceButton').addEventListener('click',()=>updateMyAttendance('confirmado'));
document.querySelector('#absenceJustification').addEventListener('change',()=>{if(myAttendance.status==='ausente')updateMyAttendance('ausente',document.querySelector('#absenceJustification').value)});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-attendance-status]');if(!button)return;button.disabled=true;const response=await fetch('/api/attendance/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_name:button.dataset.playerName,status:button.dataset.attendanceStatus})});const data=await response.json();if(!response.ok){showSuccess('Não foi possível atualizar',data.error||'Tente novamente.');button.disabled=false;return}await loadAttendance();showSuccess('Presença atualizada',`${button.dataset.playerName} foi marcado como ${button.dataset.attendanceStatus}.`);});
document.addEventListener('change',async event=>{const field=event.target.closest('.admin-justification');if(!field)return;const record=attendanceRecords[field.dataset.playerName];if(!record||record.status!=='ausente')return;const response=await fetch('/api/attendance/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_name:field.dataset.playerName,status:'ausente',justificativa:field.value})});if(response.ok){await loadAttendance();showSuccess('Justificativa salva','A justificativa de ausência foi atualizada.')}});
document.addEventListener('change',event=>{if(event.target.id!=='playerPhoto')return;const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){document.querySelector('#playerError').textContent='A foto deve ter no máximo 2 MB.';event.target.value='';return}const reader=new FileReader();reader.onload=()=>{event.target.dataset.photo=reader.result};reader.readAsDataURL(file)});
document.addEventListener('submit',async e=>{if(!['financeForm','playerForm','ruleForm','statsForm'].includes(e.target.id))return;e.preventDefault();let endpoint, payload, errorId, after;if(e.target.id==='financeForm'){endpoint='/api/finance';payload={description:document.querySelector('#financeDescription').value,amount:document.querySelector('#financeAmount').value,kind:document.querySelector('#financeKind').value};errorId='financeError';after=loadFinance}else if(e.target.id==='playerForm'){endpoint='/api/players';payload={name:document.querySelector('#playerName').value,position:document.querySelector('#playerPosition').value,foot:document.querySelector('#playerFoot').value,stars:document.querySelector('#playerStars').value,phrase:document.querySelector('#playerPhrase').value,password:document.querySelector('#playerPassword').value,jersey_number:document.querySelector('#playerJersey').value,photo_url:document.querySelector('#playerPhoto').dataset.photo||''};errorId='playerError';after=loadPlayers}else if(e.target.id==='statsForm'){endpoint=`/api/players/${e.target.dataset.playerId}/stats`;payload={stars:document.querySelector('#playerStars').value,goals:document.querySelector('#playerGoals').value,assists:document.querySelector('#playerAssists').value,games:document.querySelector('#playerGames').value,jersey_number:document.querySelector('#playerJersey').value};errorId='statsError';after=loadPlayers}else{endpoint='/api/rules';payload={title:document.querySelector('#ruleTitle').value,content:document.querySelector('#ruleContent').value};errorId='ruleError';after=loadRules}const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok){document.querySelector('#'+errorId).textContent=data.error;return}document.querySelector('#modal').classList.remove('open');after()});
document.addEventListener('click',async e=>{const button=e.target.closest('.delete-player,.delete-rule,.delete-finance');if(!button)return;const kind=button.classList.contains('delete-player')?'players':button.classList.contains('delete-rule')?'rules':'finance';if(!confirm('Excluir este item?'))return;const response=await fetch(`/api/${kind}/${button.dataset.id}`,{method:'DELETE'});if(!response.ok)return;if(kind==='players')loadPlayers();else if(kind==='rules')loadRules();else loadFinance()});
render();
loadFinance();
loadPlayers();
loadRules();
loadAttendance();

const playerFilterState={category:"all",search:""};
function applyPlayerFilters(){const groups={attack:["Atacante","Pivô"],midfield:["Meia","Ala direito","Ala esquerdo"],defense:["Fixo","Zagueiro","Goleiro"]};document.querySelectorAll("#playersList .player-row").forEach(row=>{const position=row.querySelector("[data-label=\"Posição\"]")?.textContent.trim()||"";const name=row.querySelector(".player-info b")?.textContent.toLocaleLowerCase()||"";const categoryMatches=playerFilterState.category==="all"||(groups[playerFilterState.category]||[]).includes(position);row.hidden=!(categoryMatches&&name.includes(playerFilterState.search))});const rows=[...document.querySelectorAll("#playersList .player-row")];let empty=document.querySelector("#playersList .filter-empty");if(rows.length&&!rows.some(row=>!row.hidden)){if(!empty){empty=document.createElement("p");empty.className="empty-state filter-empty";empty.textContent="Nenhum jogador encontrado para este filtro.";document.querySelector("#playersList").append(empty)}}else if(empty)empty.remove()}
document.querySelectorAll(".filter[data-filter]").forEach(button=>button.addEventListener("click",()=>{playerFilterState.category=button.dataset.filter;document.querySelectorAll(".filter[data-filter]").forEach(item=>item.classList.toggle("active",item===button));applyPlayerFilters()}));
document.querySelector("#playerSearch")?.addEventListener("input",event=>{playerFilterState.search=event.target.value.trim().toLocaleLowerCase();applyPlayerFilters()});


let profilePhotoUrl='';
function profilePhotoPreview(url,name='?'){const image=document.querySelector('#profilePhotoPreview');image.src=url||'';image.alt='Foto de perfil de '+name;image.style.display=url?'block':'none';}
async function loadProfile(){
 try{
  const response=await fetch('/api/profile');const data=await response.json();
  if(!response.ok)return;
  const player=data.player;profilePhotoUrl=player.photo_url||'';
  document.querySelector('#profileName').value=player.name||'';
  document.querySelector('#profilePosition').value=player.position||'Atacante';
  document.querySelector('#profileFoot').value=player.foot||'Destro';
  document.querySelector('#profilePhrase').value=player.phrase||'';
  document.querySelector('#profilePassword').value='';document.querySelector('#profileError').textContent='';
  profilePhotoPreview(profilePhotoUrl,player.name);
 }catch(error){}
}
document.querySelector('#profilePhoto').addEventListener('change',event=>{
 const file=event.target.files?.[0];if(!file)return;
 if(file.size>2*1024*1024){document.querySelector('#profileError').textContent='A foto deve ter no máximo 2 MB.';event.target.value='';return}
 const reader=new FileReader();reader.onload=()=>{profilePhotoUrl=reader.result;profilePhotoPreview(profilePhotoUrl,document.querySelector('#profileName').value)};reader.readAsDataURL(file);
});
document.querySelector('#profileForm').addEventListener('submit',async event=>{
 event.preventDefault();const error=document.querySelector('#profileError');error.textContent='';
 const payload={name:document.querySelector('#profileName').value,position:document.querySelector('#profilePosition').value,foot:document.querySelector('#profileFoot').value,phrase:document.querySelector('#profilePhrase').value,password:document.querySelector('#profilePassword').value,photo_url:profilePhotoUrl};
 const response=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();
 if(!response.ok){error.textContent=data.error||'Não foi possível salvar seu perfil.';return}
 updateUser(data.user);await loadPlayers();await loadAttendance();showSuccess('Perfil atualizado','Suas informações foram salvas. As estrelas permanecem sob controle da administração.');
});

document.addEventListener('click',async event=>{const button=event.target.closest('.approve-diarist');if(!button)return;button.disabled=true;const response=await fetch('/api/attendance/admin/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_name:button.dataset.playerName})});const data=await response.json();if(!response.ok){showSuccess('Não foi possível aprovar',data.error||'Tente novamente.');button.disabled=false;return}await Promise.all([loadDiarists(),loadAttendance()]);showSuccess('Confirmação aprovada',`${button.dataset.playerName} foi aprovado para a pelada.`);});
document.querySelector('[data-page="diarists"]').addEventListener('click',()=>{if(currentUser?.role==='admin')loadDiarists()});
